server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern: common
    basedir: src/main/resources/

spring:
  profiles: local
  profiles.include: 'database,fruit'
  devtolls:
    restart:
      enabled: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-test