---

spring:
  profiles: local,database,fruit
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
  datasource:
    name: SPRING-BOOT-FRUIT
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  #    hikari:
#      pool-name: SPRING-BOOT-FRUIT
#      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:

  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop


#  datasource:
#    driver-class-name: org.h2.Driver
#    platform: h2
#    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=FALSE;
#    username: sa
#    password:
  #    hikari:
#      jdbc-url: jdbc:h2:mem:testdb
#      pool-name: test123test
#      driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
##        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#
#    show-sql: true
#      settings:
#        trace: false
#        web-allow-others: false

#  datasource:
#    driver-class-name: org.h2.Driver
#    platform: h2
#    url: jdbc:h2:mem:testdb
#    #    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
##    url: jdbc:h2:file:~/test
#    username: sa
#    password:

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    #      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  profiles: dev,database
  h2:
    console:
      enabled: false

# H2 메모리 DB를 사용하기 위한 설정
datasource:
  url: jdbc:h2:mem:testdb


---
spring:
  profiles: production,database
  h2:
    console:
      enabled: false

# H2 메모리 DB를 사용하기 위한 설정
datasource:
  url: jdbc:h2:mem:testdb
---