server:
  port: 8080

spring:
  profiles:
    active: local
  profiles.include: 'database,fruit'
  devtolls:
    restart:
      enabled: true

logging:
  path: src/main/resources/logs

#  h2:
#    console:
#      enabled: true
#      path: /h2-test

#banner:
#  location: