server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern: common
#      pattern: %t %a "%r" %s (%D ms)
    basedir: src/main/resources/logs

spring:
  profiles:
    active: local
  profiles.include: 'database,fruit'
  devtolls:
    restart:
      enabled: true

logging:
  path: src/main/resources/logs


#  h2:
#    console:
#      enabled: true
#      path: /h2-test

#banner:
#  location:

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: ["*"]
#        include: ["metrics", "shutdown", "health", "threaddump", "info"]
  server:
    port: 8888
  endpoint:
    health:
      show-details: always
