---
spring:
  profiles: local,database
  h2:
    console:
      enabled: true
      path: /h2-console/
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      pool-name: test123test
      driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    show-sql: true
#      settings:
#        trace: false
#        web-allow-others: false

#  datasource:
#    driver-class-name: org.h2.Driver
#    platform: h2
#    url: jdbc:h2:mem:testdb
#    #    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
##    url: jdbc:h2:file:~/test
#    username: sa
#    password:

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    #      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  profiles: dev,database
  h2:
    console:
      enabled: false

# H2 메모리 DB를 사용하기 위한 설정
datasource:
  url: jdbc:h2:mem:testdb


---
spring:
  profiles: production,database
  h2:
    console:
      enabled: false

# H2 메모리 DB를 사용하기 위한 설정
datasource:
  url: jdbc:h2:mem:testdb
---