server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern: common
    basedir: /var/log/spring-boot-demo/


spring:
  profiles: dev
  profiles.include: 'database,fruit'
  devtolls:
    restart:
      enabled: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-test